### ISSUE TITLE
Plugin doesn't work with 3.6.3

### ISSUE THREAD

**Issue by skeetermedia** [catalyst/moodle-enrol_auto#21]
I have just installed this on ver 3.6.3, added a method to a course, set it to autoenrol on enter course.
I have tried numerous times as a user to enrol in the course and it doesn't seem to work.
the user can view the course but are not enrolled so their progress is not tracked.
what am I doing wrong?
I had this working on a 2.6 moodle with no problem

**Comment by stephanepoinsart** [comment]
Hello,

I had the same problem after an update to moodle 3.7 (from 3.5). I don't fully understand the changes to moodle 3.6 or 3.7 in this regard, and how it originally worked before the upgrade, but i think it may be caused by 2 problems : 
* course_module_viewed observer not being called on the course main page, useful when you set the plugin for "enter course" activation
* if we call the course_module_viewed observer from the main course page, the course viewed event is handled by the same code that handle the activity viewed, and the checks in that code prevent the course enrollment because it's looking to match with a specific course module that must be enabled in the plugin settings.

Anyway, here is an attempt to fix the problem : 
https://github.com/stephanepoinsart/moodle-enrol_auto/commit/1b6fdc3f8b837713be6bc919200f54c8b1112c99

I don't use other settings of the plugin beside "enroll on course view" so it may break other things.
But if it does not, i will submit a pull request.

Also, when running into problems like this, check your settings (enrollment method added and active for the course, set on "course view" for the event triggering the enrollment...)

**Comment by danmarsden** [comment]
development/support for Moodle in this plugin has stalled a bit - we don't have any Moodle sites using it on our end so keeping up on maintenance has dropped down the prioirty list - people may find the alternative plugin enrol_autoenrol useful: https://moodle.org/plugins/enrol_autoenrol
